cc_binary(
    name = "example",
    data = ["//content"],
    srcs = ["main.cc"],
    deps = [
        "//:box",
        "//:game",
        "//:screen",
        "//:sprite",
        "//:spritemap",
        "//:text",
    ],
)
